/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef ___CLUTTER_GST_MARSHAL_MARSHAL_H__
#define ___CLUTTER_GST_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:DOUBLE,DOUBLE (/home/mcatanzaro/Projects/clutter-gst/clutter-gst/clutter-gst-marshal.list:1) */
extern
void _clutter_gst_marshal_VOID__DOUBLE_DOUBLE (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* VOID:INT,INT (/home/mcatanzaro/Projects/clutter-gst/clutter-gst/clutter-gst-marshal.list:2) */
extern
void _clutter_gst_marshal_VOID__INT_INT (GClosure     *closure,
                                         GValue       *return_value,
                                         guint         n_param_values,
                                         const GValue *param_values,
                                         gpointer      invocation_hint,
                                         gpointer      marshal_data);

/* BOOL:OBJECT (/home/mcatanzaro/Projects/clutter-gst/clutter-gst/clutter-gst-marshal.list:3) */
extern
void _clutter_gst_marshal_BOOLEAN__OBJECT (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

#define _clutter_gst_marshal_BOOL__OBJECT	_clutter_gst_marshal_BOOLEAN__OBJECT


G_END_DECLS

#endif /* ___CLUTTER_GST_MARSHAL_MARSHAL_H__ */
